CREATE TABLE TASKS (
	NAME varchar(10) NOT NULL,
	DESCRIPTION text NOT NULL,
	DEADLINE TIMESTAMP NOT NULL,
	PRIORITY smallint CHECK (PRIORITY BETWEEN 0 AND 10) NOT NULL,
	PRIMARY KEY (NAME)
)

ALTER TABLE TASKS ADD COLUMN STATUS VARCHAR(20) DEFAULT 'todo';