server:
  port: 8087
  servlet:
    context-path: /zajavka
            # localhost:8087/zajavka
api:
  petStore:
    url: https://petstore3.swagger.io/api/v3/
    
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/w21
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true


#logging:
#  level:
#    root: WARN
#    pl.zajavka.api.controller: DEBUG

logging:
  level:
    org:
      springframework:
        security: DEBUG

