CREATE TABLE CUSTOMER (
	ID INT NOT NULL,
	USER_NAME VARCHAR(20) UNIQUE NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	SURNAME VARCHAR(20) NOT NULL,
	DATE_OF_BIRTH DATE,
	TELEPHONE_NUMER BIGINT
)

CREATE TABLE PRODUCER (
	ID INT,
	PRODUCER_NAME VARCHAR(20) UNIQUE NOT NULL,
	ADDRESS VARCHAR(20),
	PRIMARY KEY(ID)
)

CREATE TABLE PRODUCT (
	ID INT NOT NULL,
	PRODUCT_CODE INT UNIQUE NOT NULL,
	PRODUCT_NAME VARCHAR(50) NOT NULL,
	PRODUCT_PRICE NUMERIC(6,2) NOT NULL,
	ADULTS_ONLY BOOLEAN NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	PRODUCER_ID INT NOT NULL,
	    CONSTRAINT prodID
	    FOREIGN KEY (PRODUCER_ID)
	        REFERENCES PRODUCER (ID)
)

CREATE TABLE PURCHASE (
	ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	DATE_TIME DATE NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT customerID
		FOREIGN KEY (CUSTOMER_ID)
			REFERENCES CUSTOMER (ID),
	CONSTRAINT productID
		FOREIGN KEY (PRODUCT_ID)
			REFERENCES PRODUCT (ID)
)

CREATE TABLE OPINION (
	ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	STARS SMALLINT CHECK (STARS BETWEEN 1 AND 5) NOT NULL,
	COMMENT TEXT NOT NULL,
	DATE_TIME DATE NOT NULL,
	CONSTRAINT customerID
		FOREIGN KEY (CUSTOMER_ID)
		REFERENCES CUSTOMER (ID),
	CONSTRAINT productID
		FOREIGN KEY (PRODUCT_ID)
		REFERENCES PRODUCT (ID),
	PRIMARY KEY(ID)
)

ALTER TABLE CUSTOMER
ADD PRIMARY KEY (ID)

ALTER TABLE CUSTOMER
ADD UNIQUE (USER_NAME)