--12. Wyświetl na ekranie nazwy 10 najczęściej ocenianych produktów.

SELECT PROD.PRODUCT_NAME, COUNT(*)
FROM PRODUCT as PROD
INNER JOIN PURCHASE as PUR
ON PROD.ID = PUR.PRODUCT_ID
GROUP BY PROD.PRODUCT_NAME
ORDER BY COUNT(*) DESC
LIMIT 10
