--10. Znajdź producenta, który sprzedaje najwięcej produktów w naszym sklepie.

SELECT PRODUCE.PRODUCER_NAME, COUNT(*)
FROM PRODUCER as PRODUCE
INNER JOIN PRODUCT as PROD
ON PRODUCE.ID = PROD.PRODUCER_ID
INNER JOIN PURCHASE as PUR
ON PUR.PRODUCT_ID = PROD.ID
GROUP BY PRODUCER_NAME
ORDER BY COUNT(*) DESC
LIMIT (1)